# Generated by Django 4.1 on 2022-09-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnCaption', models.CharField(max_length=50)),
                ('DeCaption', models.CharField(max_length=50)),
                ('Url', models.CharField(max_length=100)),
            ],
        ),
    ]
